apiVersion: v1
kind: Secret
metadata:
  name: mso-access
  namespace: aci-containers-system
type: Opaque
data:
  #host: "10.66.176.111"
  host: MTAuNjYuMTc2LjExMQ==
  #username: "admin"
  username: YWRtaW4=
  #password: "123Cisco123!"
  password: MTIzQ2lzY28xMjMh

