apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubefeds.rmlab.cisco.com
spec:
  group: rmlab.cisco.com
  names:
    kind: KubeFed
    listKind: KubeFedList
    plural: kubefeds
    singular: kubefed
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha2
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      description: "MSO KubeFed"
      type: object
      properties:
        spec:
          type: object
          properties:
            tenant:
              type: string
            controller_cluster:
              type: object
              properties:
                system_id:
                  type: string
                site:
                  type: string
                node_BD_subnet:
                  type: string
                pod_Bd_subnet:
                  type: string
                l3out:
                  type: object
                  properties:
                    tenant:
                      type: string
                    name:
                      type: string
                vrf:
                  type: object
                  properties:
                    tenant:
                      type: string
                    name:
                      type: string
            worker_clusters:
              type: array
              items:
                type: object
                properties:
                  system_id:
                    type: string
                  site:
                    type: string
                  node_BD_subnet:
                    type: string
                  l3out:
                    type: object
                    properties:
                      tenant:
                        type: string
                      name:
                        type: string
                  vrf:
                    type: object
                    properties:
                      tenant:
                        type: string
                      name:
                        type: string
          required:
            - tenant
            - controller_cluster
            - worker_clusters
