apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: acicontracts.rmlab.cisco.com
spec:
  group: rmlab.cisco.com
  names:
    kind: AciContract
    listKind: AciContractList
    plural: acicontracts
    singular: acicontract
  scope: Cluster
  subresources:
    status: {}
  versions:
  - name: v1alpha2
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      description: "ACI CNI Contract"
      type: object
      properties:
        spec:
          #required: ["allow-list"]
          type: object
          properties:
            allow_list:
              type: array
              items:
                type: object
                properties:
                  protocol:
                    type: string
                    enum:
                      - icmp
                      - tcp
                      - udp
                  ports:
                    type: object
                    properties:
                      start:
                        format: int64
                        maximum: 65535
                        minimum: 1
                        type: integer
                      end:
                        format: int64
                        maximum: 65535
                        minimum: 1
                        type: integer
          required:
            - allow_list
  #additionalPrinterColumns:
  #  - name: ALLOW_LIST
  #    type: string
  #    description: The allow_list created
  #    JSONPath: .spec.allow-list
