apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: acinamespaces.rmlab.cisco.com
spec:
  group: rmlab.cisco.com
  scope: Cluster
  names:
    kind: AciNamespace
    listKind: AciNamespaceList
    plural: acinamespaces
    singular: acinamespace
    shortNames:
    - aci
  subresources:
    status: {}
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      description: "ACI CNI Namespace"
      type: object
      properties:
        spec:
          required: ["epgcontractmasters", "providedcontracts", "consumedcontracts"]
          type: object
          properties:
            epgcontractmasters:
              type: array
              items:
                type: string
            providedcontracts:
              type: array
              items:
                type: string
            consumedcontracts:
              type: array
              items:
                type: string
  additionalPrinterColumns:
    - name: EPG_CONTRACT_MASTER
      type: string
      description: The EPG Contract Master used as a template
      JSONPath: .spec.epgcontractmaster
    - name: PROVIDED_CONTRACTS
      type: string
      description: A list of provided contracts used by this EPG
      JSONPath: .spec.providedcontracts
    - name: CONSUMED_CONTRACTS
      type: string
      description: A list of consumed contracts used by this EPG
      JSONPath: .spec.consumedcontracts
