apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kents.rmlab.cisco.com
spec:
  group: rmlab.cisco.com
  names:
    kind: Kent
    listKind: KentList
    plural: kents
    singular: kent
  scope: Cluster
  subresources:
    status: {}
  versions:
  - name: v1alpha2
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      description: "ACI CNI Contract"
      type: object
      properties:
        kent-string:
          type: string
