---
- name: MSO KubeFed Operator Playbook 
  connection: local
  hosts: localhost
  vars:
    host: "{{ lookup('file', '/opt/ansible/mso-access/host') }}"
    user: "{{ lookup('file', '/opt/ansible/mso-access/username') }}"
    passwd: "{{ lookup('file', '/opt/ansible/mso-access/password') }}"
    schema: "mso_ansible_operator_{{ meta.name }}"
    desired_state: "{{ state }}"
  # TBD: Take care of the delete & update case
  tasks:
  - debug:
      msg: "host: {{ host }}, user: {{ user }}, pass: {{ passwd }}, tenant: {{ tenant }}"
  - debug:
      var: controller_cluster
  - debug:
      var: worker_clusters
  - name: Set the default site_list
    when: desired_state == 'present'
    set_fact:
      site_list: ["{{ controller_cluster.site }}"]
  - name: Set the site list
    set_fact:
      site_list: "{{ site_list + [item.site] }}"
    with_items: "{{ worker_clusters }}"
    when: (desired_state == 'present') and (item.site is defined) and (item.site not in site_list)
  - debug:
      msg: "sites: {{ site_list }}"
  - name: Add the tenant
    mso_tenant:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      tenant:  "{{ tenant }}"
      display_name: "{{ tenant }}"
      sites: "{{ site_list }}"
      use_proxy: no
      use_ssl: yes
      validate_certs: no
      #state: '{{ desired_state }}'
      state: query
  - name: Add the common tenant
    mso_tenant:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      tenant:  common
      display_name: common
      sites: "{{ site_list }}"
      use_proxy: no
      use_ssl: yes
      validate_certs: no
      state: query
      #state: '{{ desired_state }}'
  - name: Add the Common template to the schema
    mso_schema_template:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: Common
      tenant: "{{ tenant }}"
      state: '{{ desired_state }}'
      use_proxy: no
      use_ssl: yes
      validate_certs: no
  - name: Add all the sites to the Common template
    mso_schema_site:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      site: '{{ item }}'
      template: Common
      state: '{{ desired_state }}'
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    loop: "{{ site_list }}"
  - name: Add the ICMP filter entry to the Common template
    mso_schema_template_filter_entry:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: Common
      filter: KubeFed
      entry: ICMP
      ethertype: ip
      ip_protocol: icmp
      state: '{{ desired_state }}'
      use_proxy: no
      use_ssl: yes
      validate_certs: no
  - name: Add the KubeApi filter entries to the Common template
    mso_schema_template_filter_entry:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: Common
      filter: KubeFed
      entry: "kubeAPI-{{ item }}"
      ethertype: ip
      ip_protocol: tcp
      destination_from: "{{ item }}"
      destination_to: "{{ item }}"
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    loop: ["6443", "8443"]
  - name: Add KubeFed contract filter to the Common template
    mso_schema_template_contract_filter:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: Common
      contract: KubeFed
      contract_filter_type: both-way
      filter: KubeFed
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
  - name: Add the controller templates to the schema
    mso_schema_template:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: '{{ controller_cluster.system_id }}-{{ controller_cluster.site }}-{{ item }}'
      tenant: "{{ item }}"
      state: '{{ desired_state }}'
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    loop: [ "{{ tenant }}", common]
  - name: Add the site to the controller templates
    mso_schema_site:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      site: '{{ controller_cluster.site }}'
      template: '{{ controller_cluster.system_id }}-{{ controller_cluster.site }}-{{ item }}'
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    loop: [ "{{ tenant }}", common]
  - name: Add the VRF to the right controller template
    mso_schema_template_vrf:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: '{{ controller_cluster.system_id }}-{{ controller_cluster.site }}-{{ item }}'
      vrf: '{{ controller_cluster.vrf.name }}'
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    loop: [ "{{ tenant }}", common]
    when: controller_cluster.vrf.tenant == item
  # TBD: fix the l_3_out variable bug?
  - name: Add the l3out to the right controller template
    mso_schema_template_l3out:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: '{{ controller_cluster.system_id }}-{{ controller_cluster.site }}-{{ item }}'
      l3out: '{{ controller_cluster.l_3_out.name }}'
      vrf:
        template: '{{ controller_cluster.system_id }}-{{ controller_cluster.site }}-{{ controller_cluster.vrf.tenant }}'
        name: '{{ controller_cluster.vrf.name }}'
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    loop: [ "{{ tenant }}", common]
    when: controller_cluster.l_3_out.tenant == item
  - name: Add BDs to controller template
    mso_schema_template_bd:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: '{{ controller_cluster.system_id }}-{{ controller_cluster.site }}-{{ tenant }}'
      bd: 'aci-containers-{{ controller_cluster.system_id }}-{{ item }}'
      layer2_unknown_unicast: proxy
      vrf:
        template: '{{ controller_cluster.system_id }}-{{ controller_cluster.site }}-{{ controller_cluster.vrf.tenant }}'
        name: '{{ controller_cluster.vrf.name }}'
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    loop: [node-bd, pod-bd]
  - name: Add AP to the controller template
    mso_schema_template_anp:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: '{{ controller_cluster.system_id }}-{{ controller_cluster.site }}-{{ tenant }}'
      anp: 'aci-containers-{{ controller_cluster.system_id }}'
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
  - name: Add the node EPG to the controller template
    mso_schema_template_anp_epg:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: '{{ controller_cluster.system_id }}-{{ controller_cluster.site }}-{{ tenant }}'
      anp: 'aci-containers-{{ controller_cluster.system_id }}'
      epg: aci-containers-nodes
      bd:
        template: '{{ controller_cluster.system_id }}-{{ controller_cluster.site }}-{{ tenant }}'
        name: 'aci-containers-{{ controller_cluster.system_id }}-node-bd'
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
  - name: Add the kubefed EPG to the controller template
    mso_schema_template_anp_epg:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: '{{ controller_cluster.system_id }}-{{ controller_cluster.site }}-{{ tenant }}'
      anp: 'aci-containers-{{ controller_cluster.system_id }}'
      epg: '{{ controller_cluster.kubefed_epg }}'
      bd:
        template: '{{ controller_cluster.system_id }}-{{ controller_cluster.site }}-{{ tenant }}'
        name: 'aci-containers-{{ controller_cluster.system_id }}-pod-bd'
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
